### ISSUE TITLE
fix FieldSerialVersionUIDToHexadecimal

### ISSUE THREAD

**Issue by oran1248** [SpartanRefactoring/Spartanizer#1201]
Make FieldSerialVersionUIDToHexadecimal to work

**Comment by OriRoth** [comment]
There was  problem with the tipper's marking, see #1186. I think I already fixed this issue about `FieldSerialVersionUIDToHexadecimal`... is there something else? Can you give an example?

There is a way to debug the plugin, see #425.

**Comment by oran1248** [comment]
I will check it and update here

**Comment by oran1248** [comment]
Seems like it's working now.

**Comment by yossigil** [comment]
Well, the thing is that when you run the spartanizer on itself, it still does not fix all negative values.
Make a test case that fails to pinpoint the problem, and then fix it.
